/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type { RemoteResult, TypertRemoteContribution } from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { SessionNoteDeleteResult, SessionNoteWriteRequest, SessionNoteWriteResult, SessionNotesListResult } from 'dsh-session-notes'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e4e6f746573 {
    list: (agentId: SessionId) => Promise<RemoteResult<SessionNotesListResult>>
    write: (agentId: SessionId, request: SessionNoteWriteRequest) => Promise<RemoteResult<SessionNoteWriteResult>>
    delete: (agentId: SessionId, key: string) => Promise<RemoteResult<SessionNoteDeleteResult>>
  }
  interface TypertRemoteMap {
    'sessionNotes/list': (agentId: SessionId) => Promise<RemoteResult<SessionNotesListResult>>
    'sessionNotes/write': (agentId: SessionId, request: SessionNoteWriteRequest) => Promise<RemoteResult<SessionNoteWriteResult>>
    'sessionNotes/delete': (agentId: SessionId, key: string) => Promise<RemoteResult<SessionNoteDeleteResult>>
  }
  interface TypertRemoteNamespaceMap {
    sessionNotes: TypertRemoteNamespace$73657373696f6e4e6f746573
  }
  interface TypertRemoteScopeMap {
    'agent:sessionNotes/list': () => Promise<RemoteResult<SessionNotesListResult>>
    'agent:sessionNotes/write': (request: SessionNoteWriteRequest) => Promise<RemoteResult<SessionNoteWriteResult>>
    'agent:sessionNotes/delete': (key: string) => Promise<RemoteResult<SessionNoteDeleteResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
