/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const noteSchema = z.object({
  key: z.string().min(1).readonly(),
  content: z.string().min(1).readonly(),
  storedAt: z.string().regex(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC$/).readonly(),
})
const sessionIdSchema = z.string().min(1)
const listResultSchema = z.object({ notes: z.array(noteSchema).readonly() })
const writeRequestSchema = z.object({ key: z.string().min(1).readonly(), content: z.string().min(1).readonly() })
const writeResultSchema = z.object({ note: noteSchema, replaced: z.boolean().readonly() })
const deleteResultSchema = z.object({ key: z.string().min(1).readonly(), deleted: z.boolean().readonly() })

export const TYPERT = {
  package: 'dsh-session-notes',
  face: 'host',
  schemas: [],
  invocations: [
    {
      id: 'dsh-session-notes#sessionNotes/delete',
      service: 'sessionNotes',
      namespace: 'sessionNotes',
      method: 'delete',
      invocation: { kind: 'direct' },
      scope: { context: 'agent', wire: 'agentId' },
      parameters: [
        { name: 'agent', wire: 'agentId', source: 'lookup', lookup: 'agent', codec: { mode: 'strict', typeSymbol: '@deepseek-ai/dsh-session/types#SessionId', schema: sessionIdSchema } },
        { name: 'key', wire: 'key', source: 'json', codec: { mode: 'strict', typeSymbol: 'dsh-session-notes#string', schema: z.string().min(1) } },
      ],
      result: { mode: 'strict', typeSymbol: 'dsh-session-notes#SessionNoteDeleteResult', schema: deleteResultSchema },
    },
    {
      id: 'dsh-session-notes#sessionNotes/list',
      service: 'sessionNotes',
      namespace: 'sessionNotes',
      method: 'list',
      invocation: { kind: 'direct' },
      scope: { context: 'agent', wire: 'agentId' },
      parameters: [
        { name: 'agent', wire: 'agentId', source: 'lookup', lookup: 'agent', codec: { mode: 'strict', typeSymbol: '@deepseek-ai/dsh-session/types#SessionId', schema: sessionIdSchema } },
      ],
      result: { mode: 'strict', typeSymbol: 'dsh-session-notes#SessionNotesListResult', schema: listResultSchema },
    },
    {
      id: 'dsh-session-notes#sessionNotes/write',
      service: 'sessionNotes',
      namespace: 'sessionNotes',
      method: 'write',
      invocation: { kind: 'direct' },
      scope: { context: 'agent', wire: 'agentId' },
      parameters: [
        { name: 'agent', wire: 'agentId', source: 'lookup', lookup: 'agent', codec: { mode: 'strict', typeSymbol: '@deepseek-ai/dsh-session/types#SessionId', schema: sessionIdSchema } },
        { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: 'dsh-session-notes#SessionNoteWriteRequest', schema: writeRequestSchema } },
      ],
      result: { mode: 'strict', typeSymbol: 'dsh-session-notes#SessionNoteWriteResult', schema: writeResultSchema },
    },
  ],
  model: { services: [], events: [], objects: [] },
}

export default TYPERT
